name: CI/CD

on:
  push:
  pull_request:

jobs:
  test_case_generation:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.13  #${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Export test_data_create_flag
        run: python .\getConfigdata.py

      - name: Use test_data_create_flag
        run: echo "::set-output name=status:: ${{ env.TEST_DATA_CREATE_FLAG }}"

      - name: Generate Test data
        if: ${{ steps.deploy.outputs.status == 'True' }}
        run: python .\TestDataGenerationViaMetadata.py

      - name: False Step
        if: ${{ steps.deploy.outputs.status != 'True' }}
        run: echo "test_case_generation was skipped, running additional tasks."

  test_execution:
    needs: test_case_generation
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.13  #${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run tests
        run: echo "Test Execution was successful"

  test_recon:
    needs: test_execution
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.13  #${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run tests
        run: echo "test recon was successful"