name: CI/CD

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'Example input description'
        required: true
        default: 'default_value'

jobs:
  test_case_generation:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.13  #${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Export test_data_create_flag
        run: python .\getConfigdata.py

      - name: Use test_data_create_flag
        run: echo "true"


  test_execution:
    needs: test_case_generation
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Test Execution was successful"

  test_recon:
    needs: test_execution
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "test recon was successful"