name: CI/CD

on:
  workflow_dispatch:
    inputs:
      selected_group:
        description: "Select the test group to run"
        required: true
        default: "all"
        type: choice
        options:
          - physical
          - virtual
          - task1
          - task2
          - sql_to_azure
          - nas_to_azure
          - s3_to_azure

jobs:
  test_case_execution:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.13  #${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest ${{ github.event.inputs.selected_group }}