name: CI/CD

on:
  push:
  pull_request:

jobs:
  test_case_generation:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.13  #${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Export test_data_create_flag
        run: python .\getConfigdata.py

      - name: Generate Test data
        if: ${{ steps.export-flag.outputs.test_data_create_flag == "True" }}
        run: python .\TestDataGenerationViaMetadata.py

      - name: False Step
        if: ${{ steps.deploy.outputs.status == "False" }}
        run: echo "test_case_generation was skipped, running additional tasks."

  test_execution:
    needs: test_case_generation
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "test_execution was successful"

  test_recon:
    needs: test_execution
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "test_recon was successful"