name: CI/CD

on:
  workflow_dispatch:
    inputs:
      test_level:
        description: 'Workflows'
        required: true
        default: 'dataregistration'
        type: choice
        options:
          - dataregistration
          - tasks
          - end_to_end_flows
          - Priorities
      test_target:
        description: 'Components'
        required: true
        default: 'None'
        type: choice
        options:
          - All
          - P1
          - P2
          - P3
      test_parameters:
        description: 'source'
        required: true
        default: 'csv'
        type: choice
        options:
          - All
          - csv
          - xml
          - json
          - parquet
jobs:
  test_case_generation:
    #    Strategy:
    #      matrix:
    #        os: [windows-latest, ubantu-latet, macs-latest]
    #        browser: [chrome,firefox,egde]
    #      fail-fast: true
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.13  #${{ matrix.python-version }}

#      - name: Install dependencies
#        run: python -m pip install -r requirements.txt
#
#      - name: Export test_data_create_flag
#        id: export-flag
#        run: python .\getConfigdata.py

      - name: Generate Test data
        if: ${{ steps.export-flag.outputs.test_data_create_flag == 'True' }}
        run: echo "test_case_generation was success"

      - name: Skip test geneeration
        if: ${{ steps.export-flag.outputs.test_data_create_flag == 'False' }}
        run: echo "test_case_generation was skipped, running additional tasks."

  workflow_execution:
    needs: test_case_generation
    if: ${{ github.event.inputs.test_level != 'Priorities'}}
    runs-on: windows-latest
    strategy:
      matrix:
        flow:
          - sql_to_azure
          - nas_to_azure
          - s3_to_azure
          - sybase_to_azure
          - HDFS_to_Azure
          - REST_API_to_Azure
    #        os: [windows-latest, ubantu-latet, macs-latest]
    #        browser: [chrome,firefox,egde]
    #      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.13  #${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -r requirement.txt

      - name: Run pytest
        run: echo "workflow execution run matrix.flow"

  priorities_execution:
    needs: test_case_generation
    if: ${{ github.event.inputs.test_level == 'Priorities'}}
    runs-on: windows-latest
    strategy:
      matrix:
        priorities:
          - P1
          - P2
          - P3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.13  #${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -r requirement.txt

      - name: Run pytest
        run: echo "workflow execution run matrix.priorities"