name: CI/CD

on:
  workflow_dispatch:
    inputs:
      test_level:
        description: 'Workflows'
        required: true
        default: 'dataregistration'
        type: choice
        options:
          - dataregistration
          - tasks
          - end_to_end_flows
          - Priorities
      test_target:
        description: 'Components'
        required: true
        default: 'None'
        type: choice
        options:
          - All
          - P1
          - P2
          - P3
      test_parameters:
        description: 'source'
        required: true
        default: 'csv'
        type: choice
        options:
          - All
          - csv
          - xml
          - json
          - parquet
jobs:
  test_case_execution:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.13  #${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -r requirement.txt

      - name: Run pytest
        run: |
            if ( "${{ github.event.inputs.test_level }}" != "Priorities" ){
              pytest .\${{ github.event.inputs.test_level }} -m ${{ github.event.inputs.test_target }}
          }
            else{
              pytest -m ${{ github.event.inputs.test_target }}
          }